dist: trusty
sudo: required
language: java
jdk: oraclejdk8
services:
  - docker

before_install:
- docker pull postgres:10.1
- docker run -d -p 5433:5432 -e POSTGRES_PASSWORD=alfresco -e POSTGRES_USER=alfresco -e POSTGRES_DB=alfresco postgres:10.1 postgres -c 'max_connections=300'
- docker ps -a


matrix:
  include:
  - name: "AppContext01TestSuite"
    env: TEST_SUITE=AppContext01TestSuite
  - name: "AppContext02TestSuite"
    env: TEST_SUITE=AppContext02TestSuite
  - name: "AppContext03TestSuite"
    env: TEST_SUITE=AppContext03TestSuite
  - name: "AppContext04TestSuite"
    env: TEST_SUITE=AppContext04TestSuite
  - name: "AppContext05TestSuite"
    env: TEST_SUITE=AppContext05TestSuite
  - name: "AppContext06TestSuite"
    env: TEST_SUITE=AppContext06TestSuite
  script: mvn test -Dtest=$TEST_SUITE -Ddb.driver=org.postgresql.Driver -Ddb.name=alfresco -Ddb.url=jdbc:localhost:5433:alfresco -Ddb.username=alfresco -Ddb.password=alfresco --settings maven-config/settings.xml
